language: r
cache: packages
latex: false
fortran: false
env:
  - _R_CHECK_FORCE_SUGGESTS_=false

matrix:
  include:
    - dist: xenial

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick-new'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo

bioc_packages: EBImage
